version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@openinvoicebridge/*"

  - package-ecosystem: "npm"
    directory: "/apps/web-demo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@openinvoicebridge/*"

  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@openinvoicebridge/*"
